:toc:
:sectnums:
:toclevels: 5
:sectnumlevels: 5
:showcomments:
:xrefstyle: short
:icons: font
:source-highlighter: coderay
:tick: &#x2714;
:pound: &#xA3;

= Covid news

https://www.bloomberg.com/graphics/covid-vaccine-tracker-global-distribution/[Bloomberg global vaccination tracker]

https://news.sky.com/story/covid-19-uk-vaccination-tracker-find-out-how-many-have-had-the-jab-12179220[UK vaccine tracker @Sky News]

https://www.spiegel.de/international/europe/the-planning-disaster-germany-and-europe-could-fall-short-on-vaccine-supplies-a-3db4702d-ae23-4e85-85b7-20145a898abd[Germany and Europe Could Fall Short on Vaccine Supplies]

https://www.bbc.com/news/world-europe-55575756[Europe's slow start: How many people have had the Covid vaccine?]

FT (paid): https://www.ft.com/content/1d358d9e-a89e-4f26-a4d9-ba04ea78008e[Brussels probes member states’ compliance with EU Covid vaccine strategy]]

FT (paid): https://www.ft.com/content/b1444e0b-aeda-465d-b8f5-1e502c908be5[Europe’s faltering start in the vaccine race]

FT (paid): https://www.ft.com/content/119cb18b-6b8a-4588-9d4a-b2cdce5aa8f6[EU’s Covid vaccine chief defends procurement scheme]

FT (paid): https://www.ft.com/content/c1575e05-70e5-4e5f-b58c-cde5c99aba5f[EU hits back as blame game over vaccine procurement intensifies]

FT (paid): https://www.ft.com/content/f30859b3-98e6-42bb-831e-070b98b4e5de[EU set to more than double supply of BioNTech/Pfizer Covid vaccine]

FT (paid): https://www.ft.com/content/f2646ac5-aedd-4542-a211-9be83c465c6e[EU countries in blame game over sluggish vaccine rollout]

https://threadreaderapp.com/thread/1242654632305995778.html[Does Covid Virus Mutate?]

https://www.telegraph.co.uk/business/2021/01/05/changed-utterly-changed-vaccine-blunder-shook-europe/?fbclid=IwAR3NY9nl5RG3VqoLbjmcPf5ETEjIFkOsN6FeNi9ueNbPCwJWX1CgrlGJa0U[Europe's vaccine blunders]

https://www.ft.com/content/929ef3cd-8611-49b2-9f23-918dc3470166[Covid infection provides as much immunity as the Covid vaccine] - 
Researchers ‘strongly encouraged’ by findings of reinfection study among UK health workers

https://www.bmj.com/content/372/bmj.n86[BMJ - How the Oxford-AstraZeneca covid-19 vaccine was made]

https://www.cnbc.com/2021/01/12/covid-vaccine-astrazeneca-jab-could-be-distributed-in-eu-by-mid-february.html[AstraZeneca Covid vaccine could be distributed across Europe by mid-February]
The European Medicines Agency announced on Tuesday that it is now studying the results of the AstraZeneca and Oxford University vaccine
under an “accelerated timeline” and could issue its opinion as early as January 29. This jab is being rolled out in the United Kingdom since early January.

https://www.ema.europa.eu/en/news/ema-receives-application-conditional-marketing-authorisation-covid-19-vaccine-astrazeneca[European Medicines Agency receives application for conditional marketing authorisation of COVID-19 Vaccine AstraZeneca]


https://www.bbc.com/future/article/20210114-covid-19-how-effective-is-a-single-vaccine-dose[BBC: How effective is a single dose [of the Covid19 Vaccine]?]

https://www.ft.com/content/e8177df6-04ae-4d20-8e62-ca76589c7653[EU countries decry ‘very short notice’ of delay in delivery of Pfizer vaccine]
15 Jan 21: EU governments struggling with the slow rollout of coronavirus vaccines have hit out at plans by 
Pfizer to delay supplies to European countries, including the UK, from next week.

